openapi: 3.0.3
info:
  title: G_Commerce
  description: Api docs for G_Commerce intern project
  version: 1.3.0
servers:
  - url: 'http://127.0.0.1:8000/api'
  - url: "https://"

components:
  schemas:
    Attribute:
      $ref: './components/schemas.yaml#/Attribute'
    Brand:
      $ref: './components/schemas.yaml#/Brand'
    Discount:
      $ref: './components/schemas.yaml#/Discount'
    Product:
      $ref: './components/schemas.yaml#/Product'
    User:
      $ref: './components/schemas.yaml#/User'


paths:

  /register:
    $ref: './paths/user.yaml#/register'
  /verify/{slug}:
    $ref: './paths/user.yaml#/verify-{slug}'

  /verify/resend:
    $ref: './paths/user.yaml#/verify-resend'

  /login:
    $ref: './paths/user.yaml#/login'

  /logout:
    $ref: './paths/user.yaml#/logout'

  /products/create:
    $ref: './paths/products.yaml#/products-create'

  /products/{id}:
    $ref: "./paths/products.yaml#/products-{id}"
#
#components:
#
#  responses:
#    200:
#      description: verification email has been sent
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              message:
#                type: string
#                example: verify Email sent
#              data:
#                type: string
#                example: 2y10btzqnvt8tyy5qwyokuzydgbnmebxa9pwnmdalqkzqgczzmnzi9
#              code:
#                type: integer
#                example: 200
#    202:
#      description: nothing to do
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              message:
#                type: string
#                example: "JoeDoe@example.com is already Verified"
#              code:
#                type: integer
#                example: 202
#
#    401:
#      description: Token is not set
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              message:
#                type: string
#                example: Unauthenticated.
#
#    404:
#      description: Not found
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              message:
#                type: string
#                example: Not found
#              code:
#                type: integer
#                example: 404
#
#    422:
#      description: validation for payload data failed
#      content:
#        application/json:
#          schema:
#            type: object
#            properties:
#              message:
#                type: string
#                example: Validation/Login failed
#              code:
#                type: integer
#                example: 422
#              errors:
#                example:
#                  - The password field confirmation does not match.
#                  - The email field must be a valid email address.
#
#
#  #  schemas:
#  #    $ref: './openapi/components/schemas.yaml#User'
#
#
#
#
#
#
#
#
#
#
#
#  securitySchemes:
#    ApiKey:
#      description: use `Bearer ${token}`
#      type: http
#      scheme: bearer
#      name: "Authorization"







