openapi: 3.0.3
info:
  title: G_Commerce
  description: Api details for G_Commerce intern project
  version: 1.3.0
servers:
  - url: 'http://127.0.0.1:8000/api'
  - url: "https://"

components:
  schemas:
    Attribute:
      $ref: './components/schemas.yaml#/Attribute'
    Brand:
      $ref: './components/schemas.yaml#/Brand'
    Category:
      $ref: './components/schemas.yaml#/Category'
    Discount:
      $ref: './components/schemas.yaml#/Discount'
    Group:
      $ref: './components/schemas.yaml#/Group'
    Product:
      $ref: './components/schemas.yaml#/Product'
    Rating:
      $ref: './components/schemas.yaml#/Rating'

    Subcategory:
      $ref: '/components/schemas.yaml#/Subcategory'
    User:
      $ref: './components/schemas.yaml#/User'
  securitySchemes:
    ApiKey:
      $ref: './components/securitySchemas.yaml#/ApiKey'

paths:
  /register:
    $ref: './paths/user.yaml#/register'

  /verify/{slug}:
    $ref: './paths/user.yaml#/verify-{slug}'

  /verify/resend:
    $ref: './paths/user.yaml#/verify-resend'

  /login:
    $ref: './paths/user.yaml#/login'

  /logout:
    $ref: './paths/user.yaml#/logout'

  /brands/create:
    $ref: './paths/brands.yaml#/brands-create'
  /brands/{id}:
    $ref: './paths/brands.yaml#/brands-{id}'
  /brands:
    $ref: './paths/brands.yaml#/brands'

  /categories/create:
    $ref: './paths/categories.yaml#/categories-create'
  /categories/{id}:
    $ref: './paths/categories.yaml#/categories-{id}'

  /categories:
    $ref: './paths/categories.yaml#/categories'

  /coupons/create:
    $ref: './paths/coupon.yaml#/coupon-create'
  /coupons/{code}:
    $ref: './paths/coupon.yaml#/coupons-{code}'
  /coupons:
    $ref: './paths/coupon.yaml#/coupons'

  /discounts/create:
    $ref: './paths/discounts.yaml#/discounts-create'
  /discounts/{id}:
    $ref: './paths/discounts.yaml#/discounts-{id}'
  /discounts:
    $ref: './paths/discounts.yaml#/discounts'

  /groups/create:
    $ref: './paths/groups.yaml#/groups-create'
  /groups/{id}:
    $ref: './paths/groups.yaml#/groups-{id}'
  /groups:
    $ref: './paths/groups.yaml#/groups'

  /locations/create:
    $ref: './paths/location.yaml#/locations-create'
  /locations/{id}:
    $ref: './paths/location.yaml#/locations-{id}'
  /locations:
    $ref: './paths/location.yaml#/locations'


  /products/create:
    $ref: './paths/products.yaml#/products-create'
  /products/{id}:
    $ref: "./paths/products.yaml#/products-{id}"
  /products/delete/{id}:
    $ref: './paths/products.yaml#/delete-product-permanently'
  /products/{id}/rate:
    $ref: './paths/products.yaml#/products-{id}-rate'
  /products/{id}/favourite:
    $ref: './paths/products.yaml#/products-{id}-favourite'

  /products/search:
    $ref: './paths/products.yaml#/products-search'
  /products:
    $ref: './paths/products.yaml#/products'

  /subcategories/create:
    $ref: './paths/subcategories.yaml#/subcategories-create'
  /{categoryId}/subcategories:
    $ref: './paths/subcategories.yaml#/subcategories'
  #  /{slug:category}/{slug:subcategory}:
  #    $ref: './paths/subcategories.yaml#/subcategories'

  /user:
    $ref: './paths/user.yaml#/user'
  /forget-password:
    $ref: './paths/user.yaml#/forget-password'
  /forget-password/verify/{slug}:
    $ref: './paths/user.yaml#/forget-password-verify'
  /reset-password/{slug}:
    $ref: './paths/user.yaml#/reset-password'
  /forget-password/resend:
    $ref: './paths/user.yaml#/forget-password'

  /users:
    $ref: './paths/user.yaml#/users'
