products:
  get:
    summery: ''
    description: Get all Products with pagination

    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/page'
      - $ref: '../components/parameters.yaml#/limit'

    responses:
      200:
        $ref: '../components/responses.yaml#/paginatedResponse/200'

      404:
        $ref: '../components/responses.yaml#/generalResponse/404'
products-create:
  post:
    summary: Creates new product
    description: creates new product with its attributes and there value.
      <a href = "http://127.0.0.1:8000/img/NewProduct.png" target="_blank">See Code Snippet</a>
    tags:
      - Products
    requestBody:
      $ref: '../components/requestBodies.yaml#/productRequest/create'
    responses:
      201:
        $ref: '../components/responses.yaml#/generalResponse/201'
      422:
        $ref: '../components/responses.yaml#/generalResponse/422'

products-{id}:
  get:
    summary: Get one product
    description: Retrieve one product with its id
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/id'
    responses:
      200:
        $ref: '../components/responses.yaml#/productResponse/200'

  put:
    summary: ""
    description: Update product
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/id'
    requestBody:
      $ref: '../components/requestBodies.yaml#/productRequest/update'

    responses:
      200:
        $ref: '../components/responses.yaml#/generalResponse/update/200'
      404:
        $ref: '../components/responses.yaml#/generalResponse/404'
      422:
        $ref: '../components/responses.yaml#/generalResponse/422'

  delete:
    summary: "Move product to Trash NOT DONE"
    description: Delete specified product. <a href="/img/deleteProduct.png" target="_blank">code snippet</a>
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/id'
    responses:
      200:
        $ref: '../components/responses.yaml#/generalResponse/delete/200'

      404:
        $ref: '../components/responses.yaml#/generalResponse/404'

delete-product-permanently:
  delete:
    summary: "Delete product permanently NOT DONE"
    description: Delete specified product from Trash. <a href="/img/deleteProductPermanent.png" target="_blank">code snippet</a>
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/id'
    responses:
      200:
        $ref: '../components/responses.yaml#/generalResponse/delete/200'

      404:
        $ref: '../components/responses.yaml#/generalResponse/404'


products-{id}-rate:
  post:
    summery: ""
    description: Rate the product and leave your review
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/id'
    requestBody:
      $ref: '../components/requestBodies.yaml#/productRequest/rate'
    responses:
      200:
        $ref: '../components/responses.yaml#/generalResponse/200'
products-{id}-favourite:
  post:
    summery: ""
    description: Add a product to favourite list
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/id'
    security:
      - ApiKey: [ ]
    responses:
      200:
        $ref: '../components/responses.yaml#/productResponse/favourite/200'
products-search:
  get:
    description: Good
    tags:
      - Products
    parameters:
      - $ref: '../components/parameters.yaml#/products/s'
      - $ref: '../components/parameters.yaml#/products/attributes'
      - $ref: '../components/parameters.yaml#/products/brand'
      - $ref: '../components/parameters.yaml#/products/category'
      - $ref: '../components/parameters.yaml#/products/groups'
    responses:
      200:
        $ref: '../components/responses.yaml#/generalResponse/200'
