openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /products:
    get:
      tags:
        - test
      summary: This is a test
      description: this description is test
      operationId: Getproduct
      responses:
        '200':
          description: This test is for 200
          content:
            application/json:
              schema:
                type: array
