products:
  s:
    name: s
    in: query
    description: Search term
    example: IPhone

  attributes:
    name: attributes
    in: query
    description: Exact match
    example: "color:red,size:lg"

  brand:
    in: query
    name: brand
    description: Brand id
    example: 21
  category:
    in: query
    name: category
    description: Category id
    example: 13
  groups:
    in: query
    name: groups
    description: Group ids separated by comma
    schema:
      type: string
      example: 3,7
coupons:
  code:
    name: code
    in: path
    description: Coupon code to apply
    example: FRIDAYOFF

id:
  name: id
  in: path
  required: true
  allowEmptyValue: false

slug:
  name: slug
  in: path
  required: true

page:
  name: page
  in: query
  default: 1

limit:
  name: limit
  in: query
  default: 20

